"""Update document lile unique

Revision ID: f300af46e261
Revises: 23b1f0dfb3ea
Create Date: 2022-11-27 14:07:22.508080

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f300af46e261"
down_revision = "23b1f0dfb3ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_client_document", table_name="client")
    op.create_index(op.f("ix_client_document"), "client", ["document"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_document"), table_name="client")
    op.create_index("ix_client_document", "client", ["document"], unique=False)
    # ### end Alembic commands ###
