"""Add Client Model

Revision ID: 23b1f0dfb3ea
Revises: 
Create Date: 2022-11-26 23:07:46.340992

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23b1f0dfb3ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("document", sa.String(length=11), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_document"), "client", ["document"], unique=False)
    op.create_index(op.f("ix_client_name"), "client", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_name"), table_name="client")
    op.drop_index(op.f("ix_client_document"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###
