"""Add Client Model

Revision ID: 483c9aaff8a3
Revises: 
Create Date: 2022-11-26 19:57:09.544049

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "483c9aaff8a3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("document", sa.String(length=11), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_document"), "client", ["document"], unique=False)
    op.create_index(op.f("ix_client_name"), "client", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_name"), table_name="client")
    op.drop_index(op.f("ix_client_document"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###
