"""Add client column created_dt and updated_dt

Revision ID: 5a8b2785d287
Revises: 483c9aaff8a3
Create Date: 2022-11-26 21:14:24.311380

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a8b2785d287"
down_revision = "483c9aaff8a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("created_dt", postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("client", sa.Column("updated_dt", postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "updated_dt")
    op.drop_column("client", "created_dt")
    # ### end Alembic commands ###
